spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
    playlist-id: ${YOUTUBE_PLAYLIST_ID}
    application-name: ${APPLICATION_NAME}

openai:
  api:
    key: ${OPENAI_API_KEY}
    model: ${OPENAI_API_MODEL}