spring:
  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    #url: jdbc:h2:~/local
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
